const MEALS=[
 {id:'oats',name:'Protein oats',type:'Breakfast',icon:'🥣',kcal:710,p:46,c:96,f:17,ingredients:['100 g oats','300 ml low-fat milk','30 g protein powder','1 banana','15 g peanut butter','Cinnamon'],steps:['Cook the oats and milk for 4–5 minutes.','Remove from the heat and stir in the protein powder.','Top with sliced banana, cinnamon and peanut butter.']},
 {id:'eggs',name:'Eggs & toast',type:'Breakfast',icon:'🍳',kcal:690,p:48,c:55,f:30,ingredients:['4 eggs','3 slices wholegrain bread','50 g ham or turkey slices','Tomato and cucumber'],steps:['Fry or scramble the eggs to your liking.','Toast the bread and add the ham.','Serve with tomato and cucumber.']},
 {id:'pancakes',name:'Protein pancakes',type:'Breakfast',icon:'🥞',kcal:690,p:49,c:91,f:17,ingredients:['2 eggs','80 g oats','30 g protein powder','1 banana','100 ml milk','100 g berries'],steps:['Blend eggs, oats, protein powder, banana and milk.','Cook small pancakes in a non-stick pan.','Serve with berries or Skyr.']},
 {id:'wraps',name:'Chicken wraps',type:'Lunch',icon:'🌯',kcal:760,p:62,c:75,f:23,ingredients:['200 g chicken breast','2 large tortillas','30 g grated cheese','Lettuce, tomato and cucumber','50 g yoghurt dressing or salsa'],steps:['Dice and season the chicken with paprika, garlic, salt and pepper.','Fry until fully cooked through.','Warm the tortillas and fill with chicken, vegetables, cheese and dressing.']},
 {id:'taco',name:'Taco bowl',type:'Dinner',icon:'🌮',kcal:860,p:61,c:92,f:27,ingredients:['200 g lean minced beef','90 g dry rice','100 g kidney beans','Corn and lettuce','Salsa','30 g grated cheese','Taco seasoning'],steps:['Cook the rice according to the packet.','Brown the beef, add seasoning and a splash of water.','Drain the beans and assemble the bowl with all toppings.']},
 {id:'pasta',name:'Creamy chicken pasta',type:'Dinner',icon:'🍝',kcal:860,p:68,c:89,f:24,ingredients:['200 g chicken breast','100 g dry pasta','100 ml light cooking cream','Onion and spinach','Garlic','20 g parmesan'],steps:['Cook the pasta until al dente.','Fry seasoned chicken pieces until cooked through.','Add onion, spinach, garlic and cream; simmer briefly.','Mix with pasta and finish with parmesan.']},
 {id:'salmon',name:'Salmon & potatoes',type:'Dinner',icon:'🐟',kcal:810,p:49,c:75,f:34,ingredients:['200 g salmon fillet','375 g potatoes','Broccoli and carrots','50 g light sour cream','Lemon'],steps:['Cut potatoes into wedges and bake at 210°C for 30–40 minutes.','Bake the salmon for the final 12–15 minutes until cooked.','Steam the vegetables and mix sour cream with lemon, salt and pepper.']},
 {id:'curry',name:'Chicken curry',type:'Dinner',icon:'🍛',kcal:850,p:60,c:104,f:21,ingredients:['200 g chicken breast','100 g basmati rice','150 ml light coconut milk','Onion, bell pepper and broccoli','Curry paste or powder'],steps:['Cook the rice.','Fry chicken and onion until the chicken is cooked.','Add vegetables, coconut milk and curry; simmer until thickened.']},
 {id:'burger',name:'Homemade burger',type:'Dinner',icon:'🍔',kcal:910,p:59,c:96,f:31,ingredients:['200 g lean minced beef','1 burger bun','25 g cheese','300 g potatoes','Lettuce, tomato and onion','Ketchup or light dressing'],steps:['Cut and season potatoes; bake or air-fry until crisp.','Shape and season the beef, then fry until cooked through.','Build the burger with cheese, vegetables and sauce.']},
 {id:'cottage',name:'Cottage cheese bowl',type:'Snack',icon:'🍓',kcal:420,p:40,c:40,f:13,ingredients:['300 g cottage cheese','100 g frozen berries','15 g honey','15 g nuts'],steps:['Add cottage cheese to a bowl.','Top with berries, honey and nuts.']},
 {id:'shake',name:'Protein shake',type:'Snack',icon:'🥤',kcal:220,p:32,c:18,f:3,ingredients:['40 g protein powder','300 ml low-fat milk or water'],steps:['Add liquid and protein powder to a shaker.','Shake until smooth.']}
];
const DEFAULT_PLAN=[['oats','wraps','taco','cottage'],['eggs','taco','pasta','shake'],['oats','pasta','salmon','cottage'],['eggs','wraps','curry','shake'],['oats','curry','burger','cottage'],['pancakes','wraps','taco','shake'],['eggs','taco','pasta','cottage']];
const DAYS=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
const STORE_KEY='strengthfuel-v2';
const todayIndex=()=>{const d=new Date().getDay();return d===0?6:d-1};
const fresh=()=>({profile:{weight:105,activity:'moderate',goal:'recomp'},target:{kcal:2800,p:200,c:300,f:85},logs:{},plan:DEFAULT_PLAN.map(x=>[...x]),checked:{},creatine:{},progress:[],workouts:[],sessions:[]});
let state=load(),view='home',selectedDay=todayIndex(),filter='All',search='';
function load(){try{const old=JSON.parse(localStorage.getItem(STORE_KEY)||'{}');return {...fresh(),...old,profile:{...fresh().profile,...(old.profile||{})},workouts:old.workouts||[],sessions:old.sessions||[]}}catch{return fresh()}}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state))}
const dateKey=()=>new Date().toISOString().slice(0,10);
const meal=id=>MEALS.find(m=>m.id===id);
const logged=()=>state.logs[dateKey()]||[];
const portion=()=>state.target.kcal/2800;
const scaled=n=>Math.round(n*portion());
const totals=()=>logged().reduce((a,id)=>{const m=meal(id);if(m){a.kcal+=scaled(m.kcal);a.p+=scaled(m.p);a.c+=scaled(m.c);a.f+=scaled(m.f)}return a},{kcal:0,p:0,c:0,f:0});
const pct=(n,d)=>Math.min(100,Math.round(n/d*100));
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
function nav(){return `<nav class="tabs" aria-label="Main navigation">${[['home','⌂','Today'],['meals','◇','Meals'],['plan','▦','Food'],['training','⚡','Train'],['shop','✓','Shop'],['progress','↗','Progress']].map(([id,ic,l])=>`<button class="tab ${view===id?'active':''}" data-nav="${id}"><span>${ic}</span>${l}</button>`).join('')}</nav>`}
function shell(content,title='StrengthFuel'){return `<main class="app"><header class="topbar"><div class="brand"><div class="mark">S</div><div><div class="eyebrow">Strength & nutrition</div><strong>${title}</strong></div></div><button class="iconbtn" data-action="settings" aria-label="Settings">⚙</button></header>${content}</main>${nav()}`}
function home(){const t=totals(),p=Math.min(360,t.kcal/state.target.kcal*360);return shell(`
 <section class="hero"><div class="date">${new Intl.DateTimeFormat('en',{weekday:'long',month:'short',day:'numeric'}).format(new Date())}</div><h1>Fuel the work.<br>Track the result.</h1><p class="lead">One day at a time. Keep calories steady and protein high.</p><div class="rings"><div class="calorie-ring" style="--p:${p}deg"><div class="ringtext"><b>${t.kcal.toLocaleString()}</b><span>of ${state.target.kcal.toLocaleString()} kcal</span></div></div><div><div class="metric"><div class="metricline"><span>Protein</span><b>${t.p} / ${state.target.p} g</b></div><div class="track"><div class="fill" style="width:${pct(t.p,state.target.p)}%"></div></div></div><div class="metric"><div class="metricline"><span>Carbs</span><b>${t.c} / ${state.target.c} g</b></div><div class="track"><div class="fill orange" style="width:${pct(t.c,state.target.c)}%"></div></div></div></div></div></section>
 <section class="profilebar card"><div><span class="eyebrow">Personal plan</span><b>${state.profile.weight} kg · ${state.target.kcal} kcal/day</b></div><button class="linkbtn" data-action="profile">Edit</button></section><section class="section"><div class="quick"><button data-action="creatine"><span class="qicon">${state.creatine[dateKey()]?'✓':'⚡'}</span><b>Creatine</b><small>${state.creatine[dateKey()]?'5 g logged':'Log 5 g'}</small></button><button data-log="shake"><span class="qicon">🥤</span><b>Protein shake</b><small>Quick log</small></button><button data-action="checkin"><span class="qicon">⚖</span><b>Check-in</b><small>Weight & waist</small></button><button data-nav="training"><span class="qicon">🏋</span><b>Training</b><small>Plan & log</small></button></div></section>
 <section class="section"><div class="sectionhead"><h2>Today's plan</h2><button class="linkbtn" data-nav="plan">Edit plan</button></div>${state.plan[todayIndex()].map(id=>mealCard(meal(id),true)).join('')}</section>`)}
function mealCard(m,quick=false){return `<article class="card mealcard" data-open="${m.id}"><div class="mealicon">${m.icon}</div><div class="mealinfo"><h3>${m.name}</h3><p>${scaled(m.kcal)} kcal · ${scaled(m.p)} g protein</p></div>${quick?`<button class="addbtn" data-log="${m.id}" aria-label="Log ${m.name}">+</button>`:`<span class="pill">${m.type}</span>`}</article>`}
function meals(){const shown=MEALS.filter(m=>(filter==='All'||m.type===filter)&&m.name.toLowerCase().includes(search.toLowerCase()));return shell(`<h1>Meal library</h1><p class="lead">Simple ingredients from ordinary Norwegian grocery stores.</p><input class="search" id="search" placeholder="Search meals" value="${search}" aria-label="Search meals"><div class="filters">${['All','Breakfast','Lunch','Dinner','Snack'].map(x=>`<button class="filter ${filter===x?'active':''}" data-filter="${x}">${x}</button>`).join('')}</div><section class="section">${shown.length?shown.map(m=>mealCard(m)).join(''):'<div class="card empty">No meals match your search.</div>'}</section>`,'Meals')}
function plan(){return shell(`<h1>Your food week</h1><p class="lead">Portions are adjusted to ${Math.round(portion()*100)}% for your ${state.target.kcal} kcal target. Tap a day to edit meals.</p><div class="daystrip">${DAYS.map((d,i)=>`<button class="day ${selectedDay===i?'active':''}" data-day="${i}">${d}<strong>${state.plan[i].length}</strong></button>`).join('')}</div><section class="section"><div class="sectionhead"><h2>${DAYS[selectedDay]}'s meals</h2><button class="linkbtn" data-action="addmeal">+ Add meal</button></div>${state.plan[selectedDay].map((id,i)=>{const m=meal(id);return `<div class="card slot"><div class="slothead"><span>Meal ${i+1}</span></div><div class="slotmeal" data-open="${id}"><div class="mealicon">${m.icon}</div><div><h3>${m.name}</h3><span class="eyebrow">${scaled(m.kcal)} kcal · ${scaled(m.p)} g protein</span></div><button class="remove" data-remove="${i}" aria-label="Remove">×</button></div></div>`}).join('')}<button class="primary" data-action="resetplan">Reset sample week</button></section>`,'Food plan')}
function grocery(){const map={};state.plan.flat().forEach(id=>{meal(id).ingredients.forEach(raw=>{const key=raw.toLowerCase();map[key]=(map[key]||0)+1})});return Object.entries(map).map(([text,count])=>({text:text[0].toUpperCase()+text.slice(1),count})).sort((a,b)=>a.text.localeCompare(b.text))}
function shop(){const list=grocery(),done=list.filter(x=>state.checked[x.text]).length;return shell(`<h1>Shopping list</h1><p class="lead">Generated from all meals in your 7-day plan. ${done} of ${list.length} checked.</p><div class="category">This week</div><div class="card">${list.map(x=>`<label class="checkrow ${state.checked[x.text]?'checked':''}"><input type="checkbox" data-check="${encodeURIComponent(x.text)}" ${state.checked[x.text]?'checked':''}><span>${x.text}${x.count>1?` <small>× ${x.count} meals</small>`:''}</span></label>`).join('')}</div><button class="primary" data-action="clearchecks">Clear checked items</button>`,'Shop')}
function training(){const bests={};state.sessions.forEach(s=>s.entries.forEach(x=>{const load=+x.weight||0;if(!bests[x.exercise]||load>bests[x.exercise])bests[x.exercise]=load}));return shell(`<h1>Training</h1><p class="lead">Build your weekly split, log every session and watch your working weights climb.</p><div class="trainingactions"><button class="primary" data-action="newworkout">+ Create workout</button>${state.workouts.length?'<button class="secondary" data-start-workout="'+state.workouts[0].id+'">Log a session</button>':''}</div><section class="section"><div class="sectionhead"><h2>Workout plan</h2><span class="pill">${state.workouts.length} workouts</span></div>${state.workouts.length?state.workouts.map(w=>`<article class="card workout"><div class="workouttop"><div><span class="eyebrow">${w.day}</span><h3>${w.name}</h3></div><button class="addbtn" data-start-workout="${w.id}" aria-label="Log ${w.name}">▶</button></div><div class="exercisechips">${w.exercises.map(x=>`<span>${x}</span>`).join('')}</div><button class="removeworkout" data-delete-workout="${w.id}">Delete workout</button></article>`).join(''):'<div class="card empty emptybox"><b>No workouts yet</b><span>Create a workout and add exercises such as squat, bench press and deadlift.</span></div>'}</section><section class="section"><div class="sectionhead"><h2>Strength progress</h2><span class="pill">Best load</span></div>${Object.keys(bests).length?`<div class="card history">${Object.entries(bests).sort().map(([name,weight])=>`<div class="liftrow"><span>${name}</span><b>${weight} kg</b></div>`).join('')}</div>`:'<div class="card empty emptybox">Log a session to see your best weights here.</div>'}</section><section class="section"><div class="sectionhead"><h2>Recent sessions</h2></div>${state.sessions.length?`<div class="card history">${[...state.sessions].reverse().slice(0,8).map(s=>`<div class="sessionrow"><div><b>${s.name}</b><span>${s.date}</span></div><strong>${s.entries.length} exercises</strong></div>`).join('')}</div>`:'<div class="card empty emptybox">Your completed sessions will appear here.</div>'}</section>`,'Training')}
function progress(){const last=state.progress.at(-1),first=state.progress[0];const dw=last&&first?(last.weight-first.weight).toFixed(1):'—',dwaist=last&&first?(last.waist-first.waist).toFixed(1):'—';return shell(`<h1>Progress</h1><p class="lead">Recomposition is more than the scale. Track weight and waist together.</p><div class="progressgrid"><div class="card stat"><b>${last?last.weight+' kg':'—'}</b><span>Latest weight</span></div><div class="card stat"><b>${last?last.waist+' cm':'—'}</b><span>Latest waist</span></div><div class="card stat"><b>${dw==='—'?dw:(+dw>0?'+':'')+dw+' kg'}</b><span>Weight change</span></div><div class="card stat"><b>${dwaist==='—'?dwaist:(+dwaist>0?'+':'')+dwaist+' cm'}</b><span>Waist change</span></div></div><section class="section"><div class="sectionhead"><h2>Check-ins</h2><button class="linkbtn" data-action="checkin">+ Add</button></div>${state.progress.length?`<div class="card history">${[...state.progress].reverse().map(x=>`<div class="historyrow"><span>${x.date}</span><b>${x.weight} kg</b><b>${x.waist} cm</b></div>`).join('')}</div>`:'<div class="card empty">No check-ins yet. Add your first one to start the trend.</div>'}</section>`,'Progress')}
function modal(content){document.body.insertAdjacentHTML('beforeend',`<div class="modalback" data-close="1"><section class="modal" role="dialog" aria-modal="true"><div class="handle"></div>${content}</section></div>`)}
function mealModal(id){const m=meal(id);modal(`<div class="modalhead"><div><div class="eyebrow">${m.type} · ${Math.round(portion()*100)}% portion</div><h2>${m.icon} ${m.name}</h2></div><button class="close" data-close="1">×</button></div><div class="macros"><div class="macro"><b>${scaled(m.kcal)}</b><span>kcal</span></div><div class="macro"><b>${scaled(m.p)} g</b><span>protein</span></div><div class="macro"><b>${scaled(m.c)} g</b><span>carbs</span></div><div class="macro"><b>${scaled(m.f)} g</b><span>fat</span></div></div><div class="portionnote">Multiply the ingredient amounts below by <b>${portion().toFixed(2)}</b> for your personalized portion.</div><h3>Ingredients</h3><ul class="ingredients">${m.ingredients.map(x=>`<li>${x}</li>`).join('')}</ul><h3>How to make it</h3><ol class="steps">${m.steps.map(x=>`<li>${x}</li>`).join('')}</ol><button class="primary" data-log="${m.id}">Log this meal</button>`)}
function checkin(){modal(`<div class="modalhead"><div><div class="eyebrow">Progress</div><h2>New check-in</h2></div><button class="close" data-close="1">×</button></div><form id="checkform"><div class="field"><label for="weight">Weight (kg)</label><input id="weight" name="weight" type="number" min="30" max="300" step="0.1" required value="${state.progress.at(-1)?.weight||105}"></div><div class="field"><label for="waist">Waist (cm)</label><input id="waist" name="waist" type="number" min="40" max="250" step="0.1" required value="${state.progress.at(-1)?.waist||100}"></div><button class="primary">Save check-in</button></form>`)}
function profile(){modal(`<div class="modalhead"><div><div class="eyebrow">Personal nutrition</div><h2>Set your targets</h2></div><button class="close" data-close="1">×</button></div><p class="lead">Your daily calories, macros and meal portions update from these details.</p><form id="profileform"><div class="field"><label>Body weight (kg)</label><input name="weight" type="number" min="35" max="300" step="0.1" value="${state.profile.weight}" required></div><div class="field"><label>Training and daily activity</label><select name="activity"><option value="low" ${state.profile.activity==='low'?'selected':''}>Low — 1–2 sessions/week</option><option value="moderate" ${state.profile.activity==='moderate'?'selected':''}>Moderate — 3–4 sessions/week</option><option value="high" ${state.profile.activity==='high'?'selected':''}>High — 5+ sessions/week</option></select></div><div class="field"><label>Goal</label><select name="goal"><option value="lose" ${state.profile.goal==='lose'?'selected':''}>Lose fat</option><option value="recomp" ${state.profile.goal==='recomp'?'selected':''}>Body recomposition</option><option value="gain" ${state.profile.goal==='gain'?'selected':''}>Gain muscle</option></select></div><div class="estimate">This is a practical starting estimate. Adjust after 2–3 weeks based on your weight trend, energy and training.</div><button class="primary">Update my plan</button></form>`)}
function settings(){profile()}
function calculateTargets(profile){const perKg={low:27,moderate:30,high:33}[profile.activity]||30;const adjustment={lose:-300,recomp:0,gain:250}[profile.goal]||0;const kcal=Math.max(1500,Math.round((profile.weight*perKg+adjustment)/50)*50);const protein=Math.round(profile.weight*(profile.goal==='lose'?2:1.8));const fat=Math.round(profile.weight*.8);const carbs=Math.max(80,Math.round((kcal-protein*4-fat*9)/4));return{kcal,p:protein,c:carbs,f:fat}}
function newWorkout(){modal(`<div class="modalhead"><div><div class="eyebrow">Weekly training</div><h2>Create workout</h2></div><button class="close" data-close="1">×</button></div><form id="workoutform"><div class="field"><label>Workout name</label><input name="name" placeholder="e.g. Push day" required></div><div class="field"><label>Scheduled day</label><select name="day">${DAYS.map(d=>`<option>${d}</option>`).join('')}</select></div><div class="field"><label>Exercises — one per line</label><textarea name="exercises" rows="7" placeholder="Bench press&#10;Overhead press&#10;Triceps pushdown" required></textarea></div><button class="primary">Save workout</button></form>`)}
function logWorkout(id){const w=state.workouts.find(x=>x.id===id);if(!w)return;modal(`<div class="modalhead"><div><div class="eyebrow">Log session</div><h2>${w.name}</h2></div><button class="close" data-close="1">×</button></div><form id="sessionform"><input type="hidden" name="workoutId" value="${w.id}">${w.exercises.map((x,i)=>`<div class="exerciseentry"><h3>${x}</h3><input type="hidden" name="exercise_${i}" value="${x}"><div class="entrygrid"><div class="field"><label>Sets</label><input name="sets_${i}" type="number" min="1" max="20" value="3" required></div><div class="field"><label>Reps</label><input name="reps_${i}" type="number" min="1" max="100" value="8" required></div><div class="field"><label>Weight kg</label><input name="weight_${i}" type="number" min="0" max="1000" step="0.5" required></div></div></div>`).join('')}<button class="primary">Complete session</button></form>`)}
function addMeal(){modal(`<div class="modalhead"><div><div class="eyebrow">${DAYS[selectedDay]}</div><h2>Add a meal</h2></div><button class="close" data-close="1">×</button></div>${MEALS.map(m=>`<div class="card mealcard" data-addplan="${m.id}"><div class="mealicon">${m.icon}</div><div class="mealinfo"><h3>${m.name}</h3><p>${m.kcal} kcal · ${m.p} g protein</p></div><button class="addbtn">+</button></div>`).join('')}`)}
function render(){const pages={home,meals,plan,training,shop,progress};document.querySelector('#app').outerHTML=`<div id="app">${pages[view]()}</div>`}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav){view=nav.dataset.nav;render();scrollTo(0,0);return}const start=e.target.closest('[data-start-workout]');if(start){logWorkout(start.dataset.startWorkout);return}const del=e.target.closest('[data-delete-workout]');if(del){state.workouts=state.workouts.filter(x=>x.id!==del.dataset.deleteWorkout);save();render();toast('Workout deleted');return}const log=e.target.closest('[data-log]');if(log){e.stopPropagation();state.logs[dateKey()]=[...logged(),log.dataset.log];save();document.querySelector('.modalback')?.remove();render();toast('Meal logged');return}const open=e.target.closest('[data-open]');if(open){mealModal(open.dataset.open);return}const close=e.target.closest('[data-close]');if(close&&(e.target===close||close.matches('button'))){document.querySelector('.modalback')?.remove();return}const filt=e.target.closest('[data-filter]');if(filt){filter=filt.dataset.filter;render();return}const day=e.target.closest('[data-day]');if(day){selectedDay=+day.dataset.day;render();return}const rem=e.target.closest('[data-remove]');if(rem){e.stopPropagation();state.plan[selectedDay].splice(+rem.dataset.remove,1);save();render();return}const add=e.target.closest('[data-addplan]');if(add){state.plan[selectedDay].push(add.dataset.addplan);save();document.querySelector('.modalback')?.remove();render();toast('Added to plan');return}const a=e.target.closest('[data-action]');if(!a)return;({creatine(){state.creatine[dateKey()]=!state.creatine[dateKey()];save();render();toast(state.creatine[dateKey()]?'Creatine logged':'Creatine removed')},checkin,settings,profile,newworkout:newWorkout,addmeal:addMeal,resetplan(){state.plan=DEFAULT_PLAN.map(x=>[...x]);save();render();toast('Plan reset')},clearchecks(){state.checked={};save();render();toast('List cleared')}}[a.dataset.action]||(()=>{}))()});
document.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;const pos=e.target.selectionStart;render();const input=document.querySelector('#search');input.focus();input.setSelectionRange(pos,pos)}});
document.addEventListener('change',e=>{if(e.target.matches('[data-check]')){state.checked[decodeURIComponent(e.target.dataset.check)]=e.target.checked;save();render()}});
document.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);if(e.target.id==='checkform'){state.progress.push({date:new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),weight:+f.get('weight'),waist:+f.get('waist')});save();document.querySelector('.modalback').remove();view='progress';render();toast('Check-in saved')}if(e.target.id==='profileform'){state.profile={weight:+f.get('weight'),activity:f.get('activity'),goal:f.get('goal')};state.target=calculateTargets(state.profile);save();document.querySelector('.modalback').remove();render();toast('Nutrition plan updated')}if(e.target.id==='workoutform'){const exercises=f.get('exercises').split(/\n|,/).map(x=>x.trim()).filter(Boolean);state.workouts.push({id:'w'+Date.now(),name:f.get('name').trim(),day:f.get('day'),exercises});save();document.querySelector('.modalback').remove();view='training';render();toast('Workout created')}if(e.target.id==='sessionform'){const w=state.workouts.find(x=>x.id===f.get('workoutId'));const entries=w.exercises.map((exercise,i)=>({exercise,sets:+f.get('sets_'+i),reps:+f.get('reps_'+i),weight:+f.get('weight_'+i)}));state.sessions.push({id:'s'+Date.now(),workoutId:w.id,name:w.name,date:new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),entries});save();document.querySelector('.modalback').remove();view='training';render();toast('Session completed')}});
render();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
